name: job_hanting_app
description: This is an application that visualizes the selection status of the selected companies.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get: ^4.5.1
  firebase_core: ^1.10.3
  cloud_firestore: ^3.1.2
  firebase_auth: ^3.3.3
  google_sign_in: ^5.2.1
  share_plus: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
