name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b beta _flutter
          echo "${GITHUB_WORKSPACE}/_flutter/bin" >> ${GITHUB_PATH}
          
      - name: Install
        run: |
          flutter config --enable-web
          flutter pub get
          
      - name: Build
        run: flutter build web --dart-define=APIKEY=AIzaSyAA_GsHfgbMu12nCmmlrWnAf3qvDQXPA2Y \
          --dart-define=AUTHDOMAIN=job-hunting-flutter.firebaseapp.com \
          --dart-define=PROJECTID=job-hunting-flutter \
          --dart-define=STORAGEBUCKET=job-hunting-flutter.appspot.com \
          --dart-define=MESSAGINGSENDERID=680365407770 \
          --dart-define=APPID=1:680365407770:web:ccb454a8147107ca54dba3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
